apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker/docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: finagle-client
  name: finagle-client
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: finagle-client
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker/docker-compose.yml
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/docker-default: "true"
        io.kompose.service: finagle-client
    spec:
      containers:
        - args:
            - client/run
          image: finagle-client
          name: finagle-client
          resources: {}
      restartPolicy: Always
status: {}
